### ISSUE TITLE
Problems on startup

### ISSUE THREAD

**Issue by DyosTheNerd** [astrostl/nrdev#1]
Hi astrostl,
thanks for providing this package. I am new to vagrant (and github), therefore tried your projects approach on the construction of my local machine. First of all: cool technology, I wish we would use something similar at office.
However, I had two problems starting up with your description.
1: It appears that you can not use any vbox with any vagrant version. I had a vbox 4.3.16 installed and downloaded the most recent vagrant. I got some errors after the first steps in the "up" process regarding an ssl connection, which could not be opened. I after reading through the netz went back to 4.3.12, where a new up went further.
2: I get failures further down the road because of failed dependencies in Jinteki source. Any input on what I might be doing wrong?

> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[mongodb]
> /Exec[/bin/systemctl start mongodb]: Dependency Exec[/usr/bin/coffee fetch.coffe
> e] has failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[mongodb
> ]/Exec[/bin/systemctl start mongodb]: Skipping because of failed dependencies
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[lein]/Ex
> ec[/bin/systemctl start lein]: Dependency Exec[/usr/bin/coffee fetch.coffee] has
>  failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[lein]/E
> xec[/bin/systemctl start lein]: Skipping because of failed dependencies
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[stylus]/
> Exec[/bin/systemctl start stylus]: Dependency Exec[/usr/bin/coffee fetch.coffee]
>  has failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[stylus]
> /Exec[/bin/systemctl start stylus]: Skipping because of failed dependencies
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[netrunne
> r]/Exec[/bin/systemctl start netrunner]: Dependency Exec[/usr/bin/coffee fetch.c
> offee] has failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[netrunn
> er]/Exec[/bin/systemctl start netrunner]: Skipping because of failed dependencie
> s
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[mongodb]
> /Exec[/bin/systemctl enable mongodb]: Dependency Exec[/usr/bin/coffee fetch.coff
> ee] has failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[mongodb
> ]/Exec[/bin/systemctl enable mongodb]: Skipping because of failed dependencies
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[stylus]/
> Exec[/bin/systemctl enable stylus]: Dependency Exec[/usr/bin/coffee fetch.coffee
> ] has failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[stylus]
> /Exec[/bin/systemctl enable stylus]: Skipping because of failed dependencies
> ==> default: Notice: /Stage[main]/Jinteki::Service/Jinteki::Def_service[lein]/Ex
> ec[/bin/systemctl enable lein]: Dependency Exec[/usr/bin/coffee fetch.coffee] ha
> s failures: true
> ==> default: Warning: /Stage[main]/Jinteki::Service/Jinteki::Def_service[lein]/E
> xec[/bin/systemctl enable lein]: Skipping because of failed dependencies
> ==> default: Notice: Finished catalog run in 2438.24 seconds
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by DyosTheNerd** [comment]
some additional information: Windows 7, I just use putty as SSH, will try to go with something more sophisticated to test. 
Also the home folder stays empty, which is probably because of the failed build I would assume?!

**Comment by astrostl** [comment]
Howdy! Sorry I missed this, apparently didn't have notifications enabled.

VirtualBox: have you tried the latest 5.x? That's what works for me on Mac. Error: looks like a cascading failure from a failed coffee fetch. Can you try SSHing in and running that step as root manually?

**Comment by astrostl** [comment]
Closing issue, feel free to reopen
