### ISSUE TITLE
Use synced folders for local development

### ISSUE THREAD

**Issue by MaxMartin** [astrostl/nrdev#2]
Have you considered using [Vagrant's synced folders functionality](https://docs.vagrantup.com/v2/synced-folders/basic_usage.html) so that users of this project could develop on their local machine and have changes synced to the VM? It seems that otherwise you have to either edit files on the VM or manually sync the files with git every time you want to test a change. I'm messing around with trying to get this working myself, but figured I'd check and see whether you have already tried.

**Comment by astrostl** [comment]
Howdy,

Yeah, that's on the to-do. There were some issues doing it with the native `/vagrant` folder, looked like it was due to hard links. I think it'd be ideal to allow editing from both within and without.

**Comment by MaxMartin** [comment]
Rad! :metal: I was super glad to see that this project existed, because to hell with running this kind of thing locally.

**Comment by astrostl** [comment]
Yeah, the dependencies are kinda nuts, and the wiki didn't cover everything. But I don't expect any human to keep that kind of stuff up to date. When the code _is_ the documentation, it always is :D

**Comment by mattpminer** [comment]
Any progress on this? Just starting to dive in and it would be great to have this feature if it isn't there yet.

**Comment by astrostl** [comment]
I haven't actually been doing anything with the project in a while, but I agree that this is a critical feature. With a recent pull request (denoting actual use) and a couple of people now asking for it, I'll get back to it and see what can be done.

**Comment by astrostl** [comment]
Well, it went easy this time for some reason. Swear it didn't work before, I tried hard :) Anyway, the home is now `/vagrant/netrunner` within the VM, and the LOCAL `netrunner` directory outside of it. So you should be able to point an IDE over there for live development and such.

One gotcha I noticed is that it the services don't automatically start after a `vagrant halt` and `vagrant up`, but they can be started manually. Making a side-issue for that, #4
