### ISSUE TITLE
Vagrant cannot find the box

### ISSUE THREAD

**Issue by abbottmg** [astrostl/nrdev#5]
My installation (vagrant 1.84 on OS X 10.11) cannot find the 'ubuntu/vivid64' box. I do use vagrant for other projects (albeit more as a consumer), so I know I'm not having a general reachability problem. Any thoughts? Thanks!

**Comment by astrostl** [comment]
Confirmed, looks like it's no longer up at https://atlas.hashicorp.com/ubuntu . I'll have to poke around with other versions. As per the comment in the Vagrantfile, wily64 was bugged back in the day.

**Comment by astrostl** [comment]
Xenial bugged in a different way: https://bugs.launchpad.net/cloud-images/+bug/1565985

**Comment by astrostl** [comment]
Wily64 checks out now, just confirmed with a clean launch and registration. Check out the latest version of the `Vagrantfile` and you should be good to go. Thx for the report!
