### ISSUE TITLE
Box ubuntu/wily64 could not be found

### ISSUE THREAD

**Issue by haradan** [astrostl/nrdev#7]
When I ran "vagrant up" it got a 404 calling https://atlas.hashicorp.com/ubuntu/boxes/wily64/versions/20160715.0.0/providers/virtualbox.box. This box doesn't seem to exist as the external provider seems to be missing.

**Comment by astrostl** [comment]
Confirmed. That is not ideal :) Looking into it. As per comments in Vagrantfile, Xenial (the long-term support version of Ubuntu) was broken under VirtualBox.

**Comment by astrostl** [comment]
And Xenial no longer has Puppet installed, as should be standard for Vagrant images :-|

Regretting the Ubuntu decision a lot on this...

**Comment by astrostl** [comment]
```
==> default: Running provisioner: puppet...
The `puppet` binary appears not to be in the PATH of the guest. This
could be because the PATH is not properly setup or perhaps Puppet is not
installed on this guest. Puppet provisioning can not continue without
Puppet properly installed.
```

**Comment by astrostl** [comment]
Fixed up, thx for the report!
