### ISSUE TITLE
Kernel Panic- Stack is Corrupted

### ISSUE THREAD

**Issue by msbeck** [astrostl/nrdev#9]
Anybody else get kernel panics? I often do if I'm running a few terminals watching and compiling the cljs and css as well as running the server using lein repl.

I increased the RAM to about 4gb from 2gb to see if that would help in any way and it still occurs.

![screen shot 2018-02-14 at 11 53 05 am](https://user-images.githubusercontent.com/2982395/36219710-ee956cbe-117d-11e8-9507-fc5c696a62c5.png)

**Comment by astrostl** [comment]
Yikes. Looks like https://www.virtualbox.org/ticket/16417 could be in play?

The idea behind shared folder presentation was to make it a "local" experience for developers, like being able to run an IDE or code editor outside of Vagrant. Maybe it just can't handle volume.

**Comment by msbeck** [comment]
I'm not actually using the files locally, I'm doing a vagrant ssh in, so
would your findings suggest that if I turn off the file sharing that my
setup would still work and perhaps not give my kernel a panic attack?

**Comment by astrostl** [comment]
Aye, yeah, that's exactly what I'd suggest for troubleshooting.

**Comment by astrostl** [comment]
Any findings on this one @msbeck ?

**Comment by msbeck** [comment]
I've been away on vaca. Checking back in tomorrow. Thanks!
